const { handleWeatherCommand } = require('./index');

handleWeatherCommand().then((res) => {
  console.log('res', res);
});

// Example response from api.weather.gov/gridpoint/{code}/{x},{y}/forecast
// forecast.properties.periods [
//   {
//     number: 1,
//     name: 'Today',
//     startTime: '2025-07-01T10:00:00-04:00',
//     endTime: '2025-07-01T18:00:00-04:00',
//     isDaytime: true,
//     temperature: 92,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 45 },
//     windSpeed: '12 mph',
//     windDirection: 'SW',
//     icon: 'https://api.weather.gov/icons/land/day/rain_showers,20/tsra_hi,50?size=medium',
//     shortForecast: 'Slight Chance Rain Showers then Chance Light Rain',
//     detailedForecast: 'A slight chance of rain showers before 11am, then a chance of rain and isolated thunderstorms. Partly sunny, with a high near 92. Heat index values as high as 99. Southwest wind around 12 mph, with gusts as high as 24 mph. Chance of precipitation is 50%. New rainfall amounts less than a tenth of an inch possible.'
//   },
//   {
//     number: 2,
//     name: 'Tonight',
//     startTime: '2025-07-01T18:00:00-04:00',
//     endTime: '2025-07-02T06:00:00-04:00',
//     isDaytime: false,
//     temperature: 72,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 52 },
//     windSpeed: '5 to 10 mph',
//     windDirection: 'SW',
//     icon: 'https://api.weather.gov/icons/land/night/tsra,50?size=medium',
//     shortForecast: 'Chance Light Rain then Chance Showers And Thunderstorms',
//     detailedForecast: 'A chance of rain and isolated thunderstorms before 9pm, then a chance of showers and thunderstorms between 9pm and 11pm, then a chance of showers and thunderstorms. Mostly cloudy, with a low around 72. Southwest wind 5 to 10 mph, with gusts as high as 23 mph. Chance of precipitation is 50%. New rainfall amounts between a tenth and quarter of an inch possible.'
//   },
//   {
//     number: 3,
//     name: 'Wednesday',
//     startTime: '2025-07-02T06:00:00-04:00',
//     endTime: '2025-07-02T18:00:00-04:00',
//     isDaytime: true,
//     temperature: 88,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 33 },
//     windSpeed: '7 mph',
//     windDirection: 'SW',
//     icon: 'https://api.weather.gov/icons/land/day/rain_showers,30/rain_showers,20?size=medium',
//     shortForecast: 'Chance Rain Showers',
//     detailedForecast: 'A chance of rain showers before 2pm. Mostly cloudy, with a high near 88. Southwest wind around 7 mph. Chance of precipitation is 30%. New rainfall amounts less than a tenth of an inch possible.'
//   },
//   {
//     number: 4,
//     name: 'Wednesday Night',
//     startTime: '2025-07-02T18:00:00-04:00',
//     endTime: '2025-07-03T06:00:00-04:00',
//     isDaytime: false,
//     temperature: 68,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 7 },
//     windSpeed: '3 to 7 mph',
//     windDirection: 'W',
//     icon: 'https://api.weather.gov/icons/land/night/bkn?size=medium',
//     shortForecast: 'Mostly Cloudy',
//     detailedForecast: 'Mostly cloudy, with a low around 68. West wind 3 to 7 mph.'
//   },
//   {
//     number: 5,
//     name: 'Thursday',
//     startTime: '2025-07-03T06:00:00-04:00',
//     endTime: '2025-07-03T18:00:00-04:00',
//     isDaytime: true,
//     temperature: 90,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 22 },
//     windSpeed: '3 to 8 mph',
//     windDirection: 'W',
//     icon: 'https://api.weather.gov/icons/land/day/hot/tsra_hi,20?size=medium',
//     shortForecast: 'Sunny then Slight Chance Showers And Thunderstorms',
//     detailedForecast: 'A slight chance of showers and thunderstorms after 3pm. Sunny, with a high near 90. West wind 3 to 8 mph. Chance of precipitation is 20%.'
//   },
//   {
//     number: 6,
//     name: 'Thursday Night',
//     startTime: '2025-07-03T18:00:00-04:00',
//     endTime: '2025-07-04T06:00:00-04:00',
//     isDaytime: false,
//     temperature: 65,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 20 },
//     windSpeed: '7 mph',
//     windDirection: 'W',
//     icon: 'https://api.weather.gov/icons/land/night/tsra_hi,20/few?size=medium',
//     shortForecast: 'Slight Chance Showers And Thunderstorms then Mostly Clear',
//     detailedForecast: 'A slight chance of showers and thunderstorms before 9pm. Mostly clear, with a low around 65. West wind around 7 mph. Chance of precipitation is 20%.'
//   },
//   {
//     number: 7,
//     name: 'Independence Day',
//     startTime: '2025-07-04T06:00:00-04:00',
//     endTime: '2025-07-04T18:00:00-04:00',
//     isDaytime: true,
//     temperature: 84,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 4 },
//     windSpeed: '8 mph',
//     windDirection: 'NW',
//     icon: 'https://api.weather.gov/icons/land/day/few?size=medium',
//     shortForecast: 'Sunny',
//     detailedForecast: 'Sunny, with a high near 84. Northwest wind around 8 mph.'
//   },
//   {
//     number: 8,
//     name: 'Friday Night',
//     startTime: '2025-07-04T18:00:00-04:00',
//     endTime: '2025-07-05T06:00:00-04:00',
//     isDaytime: false,
//     temperature: 62,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 4 },
//     windSpeed: '2 to 6 mph',
//     windDirection: 'NW',
//     icon: 'https://api.weather.gov/icons/land/night/few?size=medium',
//     shortForecast: 'Mostly Clear',
//     detailedForecast: 'Mostly clear, with a low around 62. Northwest wind 2 to 6 mph.'
//   },
//   {
//     number: 9,
//     name: 'Saturday',
//     startTime: '2025-07-05T06:00:00-04:00',
//     endTime: '2025-07-05T18:00:00-04:00',
//     isDaytime: true,
//     temperature: 87,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 1 },
//     windSpeed: '2 to 7 mph',
//     windDirection: 'SW',
//     icon: 'https://api.weather.gov/icons/land/day/sct?size=medium',
//     shortForecast: 'Mostly Sunny',
//     detailedForecast: 'Mostly sunny, with a high near 87. Southwest wind 2 to 7 mph.'
//   },
//   {
//     number: 10,
//     name: 'Saturday Night',
//     startTime: '2025-07-05T18:00:00-04:00',
//     endTime: '2025-07-06T06:00:00-04:00',
//     isDaytime: false,
//     temperature: 68,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 7 },
//     windSpeed: '7 mph',
//     windDirection: 'S',
//     icon: 'https://api.weather.gov/icons/land/night/bkn?size=medium',
//     shortForecast: 'Mostly Cloudy',
//     detailedForecast: 'Mostly cloudy, with a low around 68. South wind around 7 mph.'
//   },
//   {
//     number: 11,
//     name: 'Sunday',
//     startTime: '2025-07-06T06:00:00-04:00',
//     endTime: '2025-07-06T18:00:00-04:00',
//     isDaytime: true,
//     temperature: 92,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 12 },
//     windSpeed: '6 to 12 mph',
//     windDirection: 'SW',
//     icon: 'https://api.weather.gov/icons/land/day/hot?size=medium',
//     shortForecast: 'Partly Sunny',
//     detailedForecast: 'Partly sunny, with a high near 92. Southwest wind 6 to 12 mph.'
//   },
//   {
//     number: 12,
//     name: 'Sunday Night',
//     startTime: '2025-07-06T18:00:00-04:00',
//     endTime: '2025-07-07T06:00:00-04:00',
//     isDaytime: false,
//     temperature: 74,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 21 },
//     windSpeed: '7 to 12 mph',
//     windDirection: 'SW',
//     icon: 'https://api.weather.gov/icons/land/night/rain_showers,20?size=medium',
//     shortForecast: 'Slight Chance Rain Showers',
//     detailedForecast: 'A slight chance of rain showers after 7pm. Mostly cloudy, with a low around 74. Southwest wind 7 to 12 mph.'
//   },
//   {
//     number: 13,
//     name: 'Monday',
//     startTime: '2025-07-07T06:00:00-04:00',
//     endTime: '2025-07-07T18:00:00-04:00',
//     isDaytime: true,
//     temperature: 94,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 25 },
//     windSpeed: '9 mph',
//     windDirection: 'SW',
//     icon: 'https://api.weather.gov/icons/land/day/rain_showers,20/tsra_hi,30?size=medium',
//     shortForecast: 'Slight Chance Rain Showers then Chance Showers And Thunderstorms',
//     detailedForecast: 'A slight chance of rain showers before 2pm, then a chance of showers and thunderstorms. Mostly sunny, with a high near 94. Southwest wind around 9 mph. Chance of precipitation is 30%.'
//   },
//   {
//     number: 14,
//     name: 'Monday Night',
//     startTime: '2025-07-07T18:00:00-04:00',
//     endTime: '2025-07-08T06:00:00-04:00',
//     isDaytime: false,
//     temperature: 73,
//     temperatureUnit: 'F',
//     temperatureTrend: '',
//     probabilityOfPrecipitation: { unitCode: 'wmoUnit:percent', value: 24 },
//     windSpeed: '5 to 8 mph',
//     windDirection: 'SW',
//     icon: 'https://api.weather.gov/icons/land/night/tsra_hi,20?size=medium',
//     shortForecast: 'Slight Chance Showers And Thunderstorms',
//     detailedForecast: 'A slight chance of showers and thunderstorms. Partly cloudy, with a low around 73. Southwest wind 5 to 8 mph.'
//   }
// ]g

// Example response from api.weather.gov/gridpoint/{code}/{x},{y}
//  {
//   '@context': [
//     'https://geojson.org/geojson-ld/geojson-context.jsonld',
//     {
//       '@version': '1.1',
//       wmoUnit: 'https://codes.wmo.int/common/unit/',
//       nwsUnit: 'https://api.weather.gov/ontology/unit/'
//     }
//   ],
//   id: 'https://api.weather.gov/gridpoints/BOX/68,90',
//   type: 'Feature',
//   geometry: { type: 'Polygon', coordinates: [ [Array] ] },
//   properties: {
//     '@id': 'https://api.weather.gov/gridpoints/BOX/68,90',
//     '@type': 'wx:Gridpoint',
//     updateTime: '2025-07-01T13:48:38+00:00',
//     validTimes: '2025-07-01T07:00:00+00:00/P8D',
//     elevation: { unitCode: 'wmoUnit:m', value: 14.0208 },
//     forecastOffice: 'https://api.weather.gov/offices/BOX',
//     gridId: 'BOX',
//     gridX: 68,
//     gridY: 90,
//     temperature: { uom: 'wmoUnit:degC', values: [Array] },
//     dewpoint: { uom: 'wmoUnit:degC', values: [Array] },
//     maxTemperature: { uom: 'wmoUnit:degC', values: [Array] },
//     minTemperature: { uom: 'wmoUnit:degC', values: [Array] },
//     relativeHumidity: { uom: 'wmoUnit:percent', values: [Array] },
//     apparentTemperature: { uom: 'wmoUnit:degC', values: [Array] },
//     wetBulbGlobeTemperature: { uom: 'wmoUnit:degC', values: [Array] },
//     heatIndex: { uom: 'wmoUnit:degC', values: [Array] },
//     windChill: { uom: 'wmoUnit:degC', values: [Array] },
//     skyCover: { uom: 'wmoUnit:percent', values: [Array] },
//     windDirection: { uom: 'wmoUnit:degree_(angle)', values: [Array] },
//     windSpeed: { uom: 'wmoUnit:km_h-1', values: [Array] },
//     windGust: { uom: 'wmoUnit:km_h-1', values: [Array] },
//     weather: { values: [Array] },
//     hazards: { values: [] },
//     probabilityOfPrecipitation: { uom: 'wmoUnit:percent', values: [Array] },
//     quantitativePrecipitation: { uom: 'wmoUnit:mm', values: [Array] },
//     iceAccumulation: { uom: 'wmoUnit:mm', values: [Array] },
//     snowfallAmount: { uom: 'wmoUnit:mm', values: [Array] },
//     snowLevel: { values: [] },
//     ceilingHeight: { uom: 'wmoUnit:m', values: [Array] },
//     visibility: { uom: 'wmoUnit:m', values: [Array] },
//     transportWindSpeed: { uom: 'wmoUnit:km_h-1', values: [Array] },
//     transportWindDirection: { uom: 'wmoUnit:degree_(angle)', values: [Array] },
//     mixingHeight: { uom: 'wmoUnit:m', values: [Array] },
//     hainesIndex: { values: [] },
//     lightningActivityLevel: { values: [] },
//     twentyFootWindSpeed: { values: [] },
//     twentyFootWindDirection: { values: [] },
//     waveHeight: { uom: 'wmoUnit:m', values: [Array] },
//     wavePeriod: { uom: 'nwsUnit:s', values: [Array] },
//     waveDirection: { values: [] },
//     primarySwellHeight: { values: [] },
//     primarySwellDirection: { values: [] },
//     secondarySwellHeight: { values: [] },
//     secondarySwellDirection: { values: [] },
//     wavePeriod2: { uom: 'nwsUnit:s', values: [Array] },
//     windWaveHeight: { uom: 'wmoUnit:m', values: [Array] },
//     dispersionIndex: { values: [] },
//     pressure: { values: [] },
//     probabilityOfTropicalStormWinds: { values: [] },
//     probabilityOfHurricaneWinds: { values: [] },
//     potentialOf15mphWinds: { values: [] },
//     potentialOf25mphWinds: { values: [] },
//     potentialOf35mphWinds: { values: [] },
//     potentialOf45mphWinds: { values: [] },
//     potentialOf20mphWindGusts: { values: [] },
//     potentialOf30mphWindGusts: { values: [] },
//     potentialOf40mphWindGusts: { values: [] },
//     potentialOf50mphWindGusts: { values: [] },
//     potentialOf60mphWindGusts: { values: [] },
//     grasslandFireDangerIndex: { values: [] },
//     probabilityOfThunder: { values: [Array] },
//     davisStabilityIndex: { values: [] },
//     atmosphericDispersionIndex: { values: [] },
//     lowVisibilityOccurrenceRiskIndex: { values: [Array] },
//     stability: { values: [] },
//     redFlagThreatIndex: { values: [] }
//   }
// }

// example gridpoint maxTemperature/minTemperature value:
// {
//   "validTime": "2025-07-03T02:00:00+00:00/PT1H",
//   "value": 60
// },

// example gridpoint weather value:
// {
//  "validTime": "2025-07-01T08:00:00+00:00/PT1H",
//  "value": [
//    {
//      "coverage": "slight_chance",
//      "weather": "rain_showers",
//      "intensity": "light",
//      "visibility": {
//        "unitCode": "wmoUnit:km",
//        "value": null
//      },
//      "attributes": []
//    }
//  ]
// },
