function smartSplit(str) {
  // Temporarily replace the "mac and cheese" and "macaroni and cheese"
  // with a placeholder to protect them from the split.
  const macAndCheese = '##MAC_AND_CHEESE##';
  const protectedStr = str
    .replace(/mac and cheese/gi, macAndCheese)
    .replace(/macaroni and cheese/gi, macAndCheese);

  // Split by " and "
  const parts = protectedStr.split(/ and /i);

  // Restore the original phrases
  return parts.map((part) =>
    part.replace(new RegExp(macAndCheese, 'g'), 'macaroni and cheese'),
  );
}

// TODO: Regex instead of string matching
// TODO: Unit tests to make sure categories are correct (order matters, so shifting things around could break)
function getCategory(itemString) {
  if (
    !itemString ||
    typeof itemString !== 'string' ||
    itemString.trim() === ''
  ) {
    console.log('itemString is empty or invalid:', itemString);
    return 'Uncategorized'; // Handle empty or invalid input
  }

  const lowerItemString = itemString.toLowerCase();

  // Define categories and associated keywords
  // Order matters: more specific categories or those with overlapping keywords should be placed earlier.
  const categoryKeywords = {
    'frozen-foods': [
      'ice cream',
      'frozen',
      'sorbet',
      'gelato',
      'popsicles',
      'waffles',
      'pancakes',
      'dumplings',
    ],
    'soups-and-canned-goods': [
      'canned',
      'pickled',
      'jarred',
      'chickpeas',
      'chicken juice',
      'artichoke hearts',
      'puree',
      'broth',
      'stock',
      'red beans',
      'black beans',
      'kidney beans',
      'refried beans',
      'paste',
      'anchovies',
      'tuna',
    ],
    meat: [
      'chicken',
      'beef',
      'pork',
      'turkey',
      'lamb',
      'sausage',
      'bacon',
      'ham',
      'ground meat',
      'steak',
      'ribs',
      'hot dog',
      'burgers',
    ],
    seafood: [
      'fish',
      'salmon',
      'tuna',
      'shrimp',
      'crab',
      'lobster',
      'cod',
      'tilapia',
      'scallops',
      'mussels',
      'clams',
    ],
    'condiments-oils-and-salad-dressings': [
      'tzatziki',
      'olives',
      'olive oil',
      'cholula',
      'tabasco',
      'sriracha',
      'hummus',
      'vegetable oil',
      'canola oil',
      'coconut oil',
      'sesame oil',
      'vinegar',
      'soy sauce',
      'sauce', // too general?
      'ketchup',
      'mustard',
      'mayonnaise',
      'jam',
      'jelly',
      'peanut butter',
      'almond butter',
      'sunbutter',
      'sun butter',
      'tahini',
      'salad dressing',
      'ranch dressing',
      'hot sauce',
      'relish',
      'salsa',
      'guacamole dip',
      'pico de gallo',
      'bbq sauce',
      'teriyaki sauce',
      'maple syrup',
      'honey',
    ],
    'grains-pasta-and-side-dishes': [
      'pizza',
      'orzo',
      'falafel',
      'pasta',
      'rice',
      'quinoa',
      'couscous',
      'stuffing mix',
      'macaroni',
      'noodles',
      'lentils',
      'dried beans',
    ],
    dairy: [
      'milk',
      'smoothie',
      'cheese',
      'parmesean',
      'mozzarella',
      'quattro formaggi',
      'yogurt',
      'butter',
      'cream cheese',
      'sour cream',
      'cottage cheese',
      'eggs',
      'egg whites',
      'almond milk',
      'soy milk',
      'oat milk',
      'tofu',
      'kefir',
      'cream',
      'half & half',
      'creamer',
    ],
    bakery: [
      'bread',
      'baguette',
      'madeline',
      'bagel',
      'croissant',
      'muffin',
      'cake',
      'pie',
      'pastry',
      'pastry',
      'tortillas',
      'rolls',
      'buns',
      'pita',
      'doughnuts',
      'cookies (bakery)',
    ],
    'breakfast-and-cereal': [
      'peanut butter puffs',
      'panda puffs',
      'cereal',
      'oats',
      'oatmeal',
      'granola',
      'pancake mix',
      'waffle mix',
      'breakfast bar',
    ],
    'snacks-cookies-and-candy': [
      'snacks',
      'pouches',
      'dried',
      'biscotti',
      'goldfish',
      'cheddar bunnies',
      'candy',
      'raisins',
      'crackers',
      'cookies',
      'clif bars',
      'larabars',
      'energy bars',
      'builder bars',
      'chips',
      'popcorn',
      'pretzels',
      'nuts',
      'almond',
      'cashews',
      'mixed nuts',
      'trail mix',
      'walnuts',
      'pecans',
      'hazelnuts',
      'pistachios',
      'brazil nuts',
      'macadamia nuts',
      'seeds',
      'dried fruit',
      'dried mango',
      'candy',
      'chocolate bar',
      'gum',
      'fruit snacks',
      'granola bars',
      'protein bars',
      'rice cakes',
      'jerky',
    ],
    beverages: [
      'water',
      'soda',
      'juice',
      'tea',
      'coffee',
      'coffee beans',
      'sports drink',
      'energy drink',
      'sparkling water',
      'kombucha',
      'coconut water',
      'powdered drink mix',
      'iced tea',
      'lemonade',
    ],
    'household-and-cleaning': [
      'paper towels',
      'rubber gloves',
      'febreeze',
      'febreze',
      'glue',
      'toilet paper',
      'napkins',
      'trash bags',
      'dish soap',
      'barkeeper', // "barkeeper's friend"
      'laundry detergent',
      'all-purpose cleaner',
      'glass cleaner',
      'sponges',
      'bleach',
      'fabric softener',
      'dishwasher detergent',
      'air freshener',
      'batteries',
      'light bulbs',
      'tissues',
      'foil',
      'plastic wrap',
      'ziploc bags',
      'freezer bags',
      'matches',
      'candles',
    ],
    'health-and-personal-care': [
      'vitamins',
      'band-aids',
      'pain reliever',
      'cold medicine',
      'sunscreen',
      'lotion',
      'feminine hygiene',
      'shampoo',
      'conditioner',
      'toothpaste',
      'deodorant',
      'hand soap',
      'body wash',
      'face wash',
      'razors',
      'shaving cream',
      'contact lens solution',
      'first aid',
      'dental floss',
      'mouthwash',
      'cotton swabs',
      'lip balm',
      'epsom salt',
    ],
    baby: [
      'diapers',
      'baby wipes',
      'formula',
      'baby food',
      'baby lotion',
      'baby shampoo',
      'pacifier',
      'baby oil',
    ],
    'pet-supplies': [
      'dog food',
      'cat food',
      'cat litter',
      'pet treats',
      'dog treats',
      'pet toys',
      'bird seed',
      'fish food',
    ],
    produce: [
      // fruits
      'apple',
      'banana',
      'orange',
      'grape',
      'strawberry',
      'watermelon',
      'blueberry',
      'raspberry',
      'avocado',
      'lemon',
      'lime',
      'melon',
      'pineapple',
      'mango',
      'kiwi',
      'peach',
      'plum',
      'pear',
      'cherry',
      'berries',
      'pomegranate',
      'nectarine',
      'apricot',
      // veg
      'salad',
      'brussels sprout',
      'brussel sprout',
      'ready veggies',
      'lettuce',
      'spinach',
      'kale',
      'tomato',
      'potato',
      'onion',
      'garlic',
      'broccoli',
      'cauliflower',
      'carrot',
      'celery',
      'peppers',
      'bell pepper',
      'jalapeno',
      'cucumber',
      'mushroom',
      'zucchini',
      'squash',
      'asparagus',
      'corn',
      'green beans',
      'peas',
      'radish',
      'beetroot',
      'sweet potato',
      'artichoke',
      'eggplant',
      'leek',
      'cabbage',
      'brussels sprouts',
      'thyme',
      'chives',
      'mint leaves',
      'basil',
      'cilantro',
    ],
    'cooking-and-baking': [
      'flour',
      'parchment',
      'sugar',
      'salt',
      'pepper',
      'spice',
      'cinnamon',
      'seasoning',
      'turmeric',
      'tumeric',
      'cumin',
      'herbs',
      'baking soda',
      'baking powder',
      'yeast',
      'chocolate chips',
      'vanilla extract',
      'cocoa powder',
      'cornstarch',
      'shortening',
      'cooking spray',
      'food coloring',
      'sprinkles',
      'broth cubes',
    ],
    'wine-beer-spirits': [
      'beer',
      'wine',
      'vodka',
      'rum',
      'whiskey',
      'gin',
      'tequila',
      'liqueur',
      'cider',
      'spirits',
    ],
    // 'other' is the fallback if no keywords match, so it typically doesn't need its own keywords
    // unless you have specific items you always want to categorize as 'other'.
  };

  // Iterate through categories and their keywords
  for (const category in categoryKeywords) {
    const keywords = categoryKeywords[category];
    for (const keyword of keywords) {
      // Use word boundaries to avoid partial matches (e.g., "apple" in "pineapple" if not careful)
      // However, for simplicity in this basic parser, we'll do a simple includes.
      // For more accuracy, regex with word boundaries `\b` would be better:
      // const regex = new RegExp(`\\b${keyword}\\b`);
      // if (regex.test(lowerItemString)) {
      if (lowerItemString.includes(keyword)) {
        // Special handling for "cream" to avoid miscategorizing "ice cream"
        if (keyword === 'cream' && lowerItemString.includes('ice cream')) {
          continue; // Skip "Dairy" if it's "ice cream", let "Frozen Foods" catch it
        }
        return category;
      }
    }
  }

  return 'other'; // Default category if no match is found
}

module.exports = { getCategory, smartSplit };
